In [1]:
import tensorflow as tf
import torch
import numpy

In [2]:
import os

os.environ["CUDA_VISIBLE_DEVICES"] = ""

In [40]:
y_true = numpy.array([[1,0,0,0], [0,1,0,0]])
y_pred = numpy.array([[0.1,0.2,0.3,0.4], [0.4,0.3,0.2,0.1]])

In [15]:
def cross_entropy(y_pred, y_true):
    # y_pred = torch.nn.functional.softmax(y_pred, dim=-1)
    category = y_pred.size()[-1]
    y_true = torch.nn.functional.one_hot(y_true, num_classes=category)
    loss = - (y_true * torch.log(y_pred) + (1-y_true) * torch.log(1-y_pred))
    return torch.mean(torch.sum(loss, dim=-1))

In [16]:
s1 = cross_entropy(torch.Tensor(y_pred), torch.argmax(torch.Tensor(y_true), dim=-1))
print(s1)

tensor(2.7183)


In [10]:
s2 = torch.nn.CrossEntropyLoss()(torch.Tensor(y_pred), torch.argmax(torch.Tensor(y_true), dim=-1))
print(s2)

tensor(1.4425)


In [12]:
s3 = tf.keras.losses.CategoricalCrossentropy()(y_true, y_pred)
print(s3)

tf.Tensor(1.7532789707183838, shape=(), dtype=float64)


In [21]:
def cross_entropy_v2(y_pred, y_true):
    # y_pred = torch.nn.functional.softmax(y_pred, dim=-1)
    category = y_pred.size()[-1]
    y_true = torch.nn.functional.one_hot(y_true, num_classes=category)
    loss = - y_true * torch.log(y_pred)
    return torch.mean(torch.sum(loss, dim=-1))

In [22]:
s4 = cross_entropy_v2(torch.Tensor(y_pred), torch.argmax(torch.Tensor(y_true), dim=-1))
print(s4)

tensor(1.7533)


In [32]:
def cross_entropy_v2(y_pred, y_true):
    y_pred = torch.nn.functional.softmax(y_pred, dim=-1)                 
    category = y_pred.size()[-1]
    y_true = torch.nn.functional.one_hot(y_true, num_classes=category)
    loss = - y_true * torch.log(y_pred)
    return torch.mean(torch.sum(loss, dim=-1))

In [33]:
s5 = cross_entropy_v2(torch.Tensor(y_pred), torch.argmax(torch.Tensor(y_true), dim=-1))
print(s5)

tensor(1.4425)


In [44]:
def cross_entropy_v4(y_true, y_pred):
    loss = -y_true * tf.math.log(y_pred)
    return tf.reduce_mean(tf.reduce_sum(loss, axis=1))

s6 = cross_entropy_v4(y_true, y_pred)
print(s6)

tf.Tensor(1.753278948659991, shape=(), dtype=float64)


In [42]:
# tf.math.log(numpy.array([[0.1,0.2,0.3,0.4], [0.4,0.3,0.2,0.1]]))

<tf.Tensor: shape=(2, 4), dtype=float64, numpy=
array([[-2.30258509, -1.60943791, -1.2039728 , -0.91629073],
       [-0.91629073, -1.2039728 , -1.60943791, -2.30258509]])>

In [45]:
def cross_entropy_v5(y_true, y_pred):
    y_pred = tf.nn.softmax(y_pred, axis=-1)
    loss = -y_true * tf.math.log(y_pred)
    return tf.reduce_mean(tf.reduce_sum(loss, axis=1))

s7 = cross_entropy_v5(y_true, y_pred)
print(s7)

tf.Tensor(1.4425355294551627, shape=(), dtype=float64)


In [46]:
s8 = tf.keras.losses.CategoricalCrossentropy(from_logits=True)(y_true, y_pred)
print(s8)

tf.Tensor(1.4425355195999146, shape=(), dtype=float64)


In [66]:
y_true = numpy.array([[1,0],[2,3]])
y_pred = numpy.array([[[0.1,0.2,0.3,0.4], [0.4,0.3,0.2,0.1]], [[0.1,0.2,0.3,0.4], [0.4,0.3,0.2,0.1]]])
print(y_true.shape)
print(y_pred.shape)
print(y_pred)

(2, 2)
(2, 2, 4)
[[[0.1 0.2 0.3 0.4]
  [0.4 0.3 0.2 0.1]]

 [[0.1 0.2 0.3 0.4]
  [0.4 0.3 0.2 0.1]]]


In [67]:
torch.nn.CrossEntropyLoss()(torch.tensor(y_pred.swapaxes(1,2)), torch.tensor(y_true))

tensor(1.3925, dtype=torch.float64)

In [51]:
def cross_entropy(y_pred, y_true):
    num_classes = y_pred.size()[-1]
    y_pred = torch.nn.functional.softmax(y_pred, dim=-1)
    y_true = torch.nn.functional.one_hot(y_true, num_classes=num_classes)
    loss = - y_true * torch.log(y_pred)
    return torch.mean(torch.sum(loss, dim=-1))

In [55]:
y_true = numpy.array([[1,0],[2,3]])
y_pred = numpy.array([[[0.1,0.2,0.3,0.4], [0.4,0.3,0.2,0.1]], [[0.1,0.2,0.3,0.4], [0.4,0.3,0.2,0.1]]])
cross_entropy(torch.Tensor(y_pred), torch.LongTensor(y_true))

tensor(1.3925)

In [60]:
def cross_entropy(y_pred, y_true):
    y_pred = torch.tensor(y_pred)
    y_true = torch.tensor(y_true, dtype=torch.long)
    num_classes = y_pred.size()[-1]
    y_true = torch.nn.functional.one_hot(y_true, num_classes=num_classes)
    loss = - y_true * torch.log(y_pred)
    return torch.mean(torch.sum(loss, dim=-1))

y_true = numpy.array([[1,0],[2,3]])
y_pred = numpy.array([[[0.1,0.2,0.3,0.4], [0.4,0.3,0.2,0.1]], [[0.1,0.2,0.3,0.4], [0.4,0.3,0.2,0.1]]])
print(cross_entropy(y_pred, y_true))
print(tf.keras.losses.CategoricalCrossentropy()(tf.one_hot(y_true, 4), y_pred))

tensor(1.5081, dtype=torch.float64)
tf.Tensor(1.5080716609954834, shape=(), dtype=float64)


In [27]:
y_true = torch.LongTensor([[1,0], [2,3]])
torch.nn.functional.one_hot(y_true, num_classes=4)

tensor([[[0, 1, 0, 0],
         [1, 0, 0, 0]],

        [[0, 0, 1, 0],
         [0, 0, 0, 1]]])

In [33]:
y_true = torch.tensor([[1,0], [2,3]], dtype=torch.long)
torch.nn.functional.one_hot(y_true, num_classes=4)

tensor([[[0, 1, 0, 0],
         [1, 0, 0, 0]],

        [[0, 0, 1, 0],
         [0, 0, 0, 1]]])

In [20]:
torch.nn.functional.one_hot(torch.arange(0, 5) % 3)

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [1, 0, 0],
        [0, 1, 0]])

In [24]:
torch.arange(0, 6).view(3,2) % 3

tensor([[0, 1],
        [2, 0],
        [1, 2]])

In [25]:
torch.Tensor([[1,0], [2,3]])

tensor([[1., 0.],
        [2., 3.]])

In [68]:
y_true = numpy.array([[1,0],[2,3]])
y_pred = numpy.array([[[0.1,0.2,0.3,0.4], [0.4,0.3,0.2,0.1]], [[0.1,0.2,0.3,0.4], [0.4,0.3,0.2,0.1]]])

torch.nn.CrossEntropyLoss()(torch.tensor(y_pred.swapaxes(1,2)), torch.tensor(y_true))
# tensor(1.3925, dtype=torch.float64)

tf.keras.losses.CategoricalCrossentropy()(tf.one_hot(y_true, 4), tf.nn.softmax(y_pred))

<tf.Tensor: shape=(), dtype=float64, numpy=1.3925354480743408>

## 结论

In [3]:
y_true = numpy.array([[1,0],[2,3]])
y_pred = numpy.array([[[0.1,0.2,0.3,0.4], [0.4,0.3,0.2,0.1]], [[0.1,0.2,0.3,0.4], [0.4,0.3,0.2,0.1]]])

### 1. tensorflow

In [4]:
tf.keras.losses.SparseCategoricalCrossentropy()(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float64, numpy=1.5080716609954834>

In [5]:
tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float64, numpy=1.3925354480743408>

In [7]:
tf.keras.losses.CategoricalCrossentropy()(tf.one_hot(y_true, 4), y_pred)

<tf.Tensor: shape=(), dtype=float64, numpy=1.5080716609954834>

In [8]:
tf.keras.losses.CategoricalCrossentropy(from_logits=True)(tf.one_hot(y_true, 4), y_pred)

<tf.Tensor: shape=(), dtype=float64, numpy=1.3925354480743408>

### 2. pytorch

In [9]:
def cross_entropy(y_pred, y_true, from_logits=False):
    num_classes = y_pred.size()[-1]
    if from_logits:
        y_pred = torch.nn.functional.softmax(y_pred, dim=-1)
    y_true = torch.nn.functional.one_hot(y_true, num_classes=num_classes)
    loss = - y_true * torch.log(y_pred)
    return torch.mean(torch.sum(loss, dim=-1))

In [11]:
cross_entropy(torch.tensor(y_pred), torch.tensor(y_true), from_logits=False)

tensor(1.5081, dtype=torch.float64)

In [12]:
cross_entropy(torch.tensor(y_pred), torch.tensor(y_true), from_logits=True)

tensor(1.3925, dtype=torch.float64)

In [17]:
torch.nn.CrossEntropyLoss()(torch.tensor(y_pred.swapaxes(1,2)), torch.tensor(y_true))

tensor(1.3925, dtype=torch.float64)

In [18]:
torch.nn.CrossEntropyLoss()(torch.tensor(y_pred).transpose(1,2), torch.tensor(y_true))

tensor(1.3925, dtype=torch.float64)